import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const ImagesEditor = () => {
    return (

        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.center}>
                  
                </div>
                <Link href="./images-editor" className={styles.description}>
                    <p>
                        Go back
                    </p>
                </Link>
            </main>
        </>

    )

}

export default ImagesEditor;